on:
  push:
    branches:
      - master
    tags:
      - "*"
jobs:
  build:
    strategy:
      matrix:
        os:
          - "windows-2019"
          - "ubuntu-18.04"
          - "macos-latest"
        extension:
          - ""
          - ".exe"
        exclude:
          - os: "windows"
            extension: ""
          - os: "ubuntu-18.04"
            extension: ".exe"
          - os: "macos-latest"
            extension: ".exe"
    runs-on: "${{ matrix.os }}"
    name: "build binary"
    steps:
      - name: "build-release-binary"
        run: cargo build --release
      - name: "collect-binary"
        uses: "actions/upload-artifact@1"
        with:
          name: "binary-${{matrix.os}}"
          path: "target/release/bsp${{matrix.extension}}"
        
    
