on:
  push:
    branches:
      - master
    tags:
      - "*"
jobs:
  build:
    strategy:
      matrix:
        os:
          - "windows-2019"
          - "ubuntu-18.04"
          - "macos-latest"
        binname:
          - "bsp"
          - "bsp.exe"
        exclude:
          - os: "windows"
            binname: "bsp"
          - os: "ubuntu-18.04"
            binname: "bsp.exe"
          - os: "macos-latest"
            binname: "bsp.exe"
    runs-on: "${{ matrix.os }}"
    name: "build binary"
    steps:
      - name: "checkout-repo"
        uses: "actions/checkout@v1"
      - name: "build-release-binary"
        run: cargo build --release
      - name: "collect-binary"
        uses: "actions/upload-artifact@v1"
        with:
          name: "binary-${{ matrix.os }}"
          path: "target/release/${{ matrix.binname }}"
        
    
