on:
  push:
    branches:
      - master
    tags:
      - "*"
jobs:
  build:
    strategy:
      matrix:
        os:
          - "windows-2019"
          - "ubuntu-18.04"
          - "macos-latest"
        binname:
          - "bsp"
          - "bsp.exe"
        triplet:
          - "x86_64-pc-windows-msvc"
          - "x86_64-unknown-linux-gnu"
          - "x86_64-apple-darwin"
        exclude:
          - os: "windows-2019"
            binname: "bsp"
          - os: "ubuntu-18.04"
            binname: "bsp.exe"
          - os: "macos-latest"
            binname: "bsp.exe"
          - os: "windows-2019"
            triplet: "x86_64-unknown-linux-gnu"
          - os: "windows-2019"
            triplet: "x86_64-apple-darwin"
          - os: "ubuntu-18.04"
            triplet: "x86_64-pc-windows-msvc"
          - os: "ubuntu-18.04"
            triplet: "x86_64-apple-darwin"
          - os: "macos-latest"
            triplet: "x86_64-pc-windows-msvc"
          - os: "macos-latest"
            triplet: "x86_64-unknown-linux-gnu"
    runs-on: "${{ matrix.os }}"
    name: "build binary"
    steps:
      - name: "checkout-repo"
        uses: "actions/checkout@v1"
      - name: "build-release-binary"
        run: cargo build --release
      - name: "collect-binary"
        uses: "actions/upload-artifact@v1"
        with:
          name: "bin-${{ matrix.triplet }}"
          path: "target/release/${{ matrix.binname }}"
      - name: "collect-pdb"
        uses: "actions/upload-artifact@v1"
        with:
          name: "pdb-${{ matrix.os }}"
          path: "target/release/bsp.pdb"
        if: matrix.os == 'windows-2019'
        
    
